[workspace]
resolver = "2"
members = [
    "cvlr",
    "cvlr-asserts",
    "cvlr-mathint",
    "cvlr-log",
    "cvlr-nondet",
    "cvlr-early-panic",
    "cvlr-hook",
    "cvlr-macros",
    "cvlr-fixed"
]

[workspace.package]
version = "0.4.0"
authors = [
    "Arie Gurfinkel <arie@certora.com>",
    "Jorge A. Navas <jorge@certora.com>",
    "Francesco Parolini <francesco@certora.com>",
    "Chandrakana Nandi <chandra@certora.com>",
    "Alexander Bakst <abakst@certora.com>",
]
edition = "2021"
description = "Certora Verification Language for Rust"
documentation = "https://docs.rs/cvlr/latest"
license = "MIT"
keywords = [
    "certora", 
    "assert", 
    "logic", 
    "verification", 
    "formal-methods",
]
categories = [
    "development-tools::debugging", 
    "development-tools::testing", 
    "no-std"
]
readme = "README.md"
homepage = "https://www.certora.com"
repository = "https://github.com/Certora/cvlr"

[workspace.dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
macrotest = "1"
trybuild = "1"

cvlr = { path = "cvlr", version = "=0.4.0" }
cvlr-asserts = { path = "cvlr-asserts", version = "=0.4.0" }
cvlr-mathint = { path = "cvlr-mathint", version = "=0.4.0" }
cvlr-nondet = { path = "cvlr-nondet", default-features = false, version = "=0.4.0" }
cvlr-log = { path = "cvlr-log", version = "=0.4.0" }
cvlr-macros = { path = "cvlr-macros", version = "=0.4.0" }
cvlr-early-panic = { path = "cvlr-early-panic", version = "=0.4.0" }
cvlr-hook = { path = "cvlr-hook", version = "=0.4.0" }
cvlr-fixed = { path = "cvlr-fixed", version = "=0.4.0" }