[package]
name = "cvlr-fixed"
description = "Fixed point numbers over Certora native integers" 
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true


[features]
rt = ["cvlr-mathint/rt", "cvlr-nondet/rt", "cvlr-asserts/rt", "cvlr-log/rt"]

[dependencies]
cvlr-nondet = { workspace = true, default-features = false }
cvlr-asserts = { workspace = true }
cvlr-mathint = { workspace = true }
cvlr-log = { workspace = true }
