[package]
name = "cvlr-mathint"
description = "Number library backed by Certora native integers"
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true


[features]
default = []
rt = []

[dependencies]
cvlr-nondet = { workspace = true, default-features = false }
cvlr-asserts = { workspace = true }

[dev-dependencies]
cvlr-mathint = { path = ".", features = ["rt"] }