[package]
name = "cvlr-hook"
description = "Macro to inject code at a function call"
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true


[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "derive"] }
quote = { workspace = true }

[dev-dependencies]
macrotest = { workspace = true }
trybuild = { workspace = true }

